// Hoja de estilos
import { StyleSheet } from 'react-native';
import { MaxContentWidth } from '@/constants/theme';

export const createReportsStyles = (theme:any) => StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  innerContainer: {
    maxWidth: MaxContentWidth,
    width: '100%',
    alignSelf: 'center',
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.pageTitle,
    fontFamily: 'Open Sans',
    marginBottom: 6,
  },
  screenSubtitle: {
    fontSize: 14,
    color: theme.pageSubtitle,
    fontFamily: 'Open Sans',
    lineHeight: 20,
    marginBottom: 20,
  },
  filterSection: {
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.fieldLabel,
    fontFamily: 'Open Sans',
    marginBottom: 6,
  },
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.backgroundElement,
    borderWidth: 1,
    borderColor: theme.cardSeparator,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectButtonText: {
    fontSize: 14,
    color: theme.textNames,
    fontFamily: 'Open Sans',
    flex: 1,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  kpiCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.backgroundElement,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  chartCard: {
    backgroundColor: theme.backgroundElement,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.cardSeparator,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.main,
    fontFamily: 'Open Sans',
  },
  periodFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: theme.backgroundSecondary,
    borderWidth: 1,
    borderColor: theme.cardSeparator,
  },
  periodFilterText: {
    fontSize: 12,
    color: theme.pageSubtitle,
    fontFamily: 'Open Sans',
    fontWeight: '500',
  },
  filterIcon: {
    marginLeft: 4,
  },
  stateContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  stateText: {
    fontSize: 13,
    color: theme.pageSubtitle,
    fontFamily: 'Open Sans',
  },
  emptyContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.backgroundSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.tooltipLegend,
  },
  emptyText: {
    fontSize: 14,
    color: theme.breadcrumbSeparator,
    textAlign: 'center',
    fontFamily: 'Open Sans',
    lineHeight: 20,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginBottom: 20,
  },
  printBtn: {
    width: 44,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.cardSeparator,
    backgroundColor: theme.backgroundElement,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pdfBtn: {
    flexDirection: 'row',
    height: 38,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: theme.main,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.main,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  pdfBtnText: {
    color: theme.overMain,
    fontWeight: '700',
    fontSize: 13,
    letterSpacing: 0.5,
  },
  kpiRowThree: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
});